import { defineStore } from 'pinia'
import { ref } from 'vue'
import useAppStoreState from './state.js'


import { useAuthActions } from './authActions.js'
import { createShardedActions } from '@xbensommo/shard-provider';

import shardProvider  from '@/stores/appStore/provider.js'
// @generated by Totistack
// @created 2026-02-12T08:42:24.519Z

export const useAppStore = defineStore('appStore', () => {
  const state = useAppStoreState()

  
  const authActions = useAuthActions(state, ["users"])
  

  // 2. Generate Generic Actions for all collections
  const actions = {};
  const collectionNames = Object.keys(state).filter(key => 
    !['loading', 'error', 'currentUser', 'authInitialized', 'isLoading'].includes(key)
  );

  /**
   * 
   * // 2. Inject Specialized Logic
  const extras = specializedLogic(state, allActions);
  Object.keys(extras).forEach(col => {
    Object.assign(allActions[col], extras[col]);
  });
   * */

  collectionNames.forEach(colName => {
    // This gives us: add, update, remove, fetchByFilters, etc., for EVERY collection
    actions[`${colName}Actions`] = createShardedActions(colName, state, shardProvider);
  });

  const showLoading = () => (state.isLoading.value = true)
  const hideLoading = () => (state.isLoading.value = false)

  return {
    ...state,
    ...authActions,
    ...actions, // Access via: store.auctionsActions.add()
    showLoading,
    hideLoading
  }
})
