/**
 * @title Router Configuration
 * @description Vue Router with 1-hour caching and enterprise guards
 * @generated by Totistack
 * @path src/router/index.js
 */

/**
 * @title Project Router Implementation
 * @path src/router/index.js
 */
import { createEnterpriseRouter, createLazyHelper } from '@/packages/enterprise-router.js' // The file above
import { useAppStore } from '@/stores/appStore' // Your specific store
import { publicRoutes } from './routes/publicRoutes'
import { adminRoutes } from './routes/adminRoutes'
import { authRoutes } from './routes/authRoutes'
import { clientRoutes }  from './routes/clientRoutes'

// 1. Define your specific View Loader
// This keeps the "lazy" magic but lets you change folder structure per project
const lazy = createLazyHelper((view, dir) => {
    return dir 
        ? import(`@/views/${dir}/${view}.vue`) 
        : import(`@/views/${view}.vue`)
})

// 2. Initialize
const router = createEnterpriseRouter({
    // A. Pass your routes
    routes: [
        publicRoutes(lazy), // Pass lazy helper if routes need it
        adminRoutes(lazy),
        clientRoutes(lazy),
        authRoutes(lazy),

        {
            path: '/logout',
            name: 'Logout',
            beforeEnter: async (to, from, next) => {
                const store = useAppStore();
                try {
                    // Call the store logout method
                    await store.logout(); 
                    
                    // Redirect with a success flag
                    next({ 
                        name: 'Login', 
                        query: { message: 'Successfully logged out', type: 'success' } 
                    });
                } catch (error) {
                    console.error('Logout failed', error);
                    next({ name: '500' });
                }
            },
            component: () => null 
        },
    ],

    // B. Pass your Store Hook
    useStore: useAppStore,

    // C. Configure Settings
    settings: {
        appName: 'Nangura Social Care',
        googleAnalyticsId: import.meta.env.VITE_GA_MEASUREMENT_ID,
        sensitiveRoles: ['admin', 'user', 'practitioner']
    },

    // D. The Adapter: Map YOUR store to the ROUTER'S generic needs
    // This allows you to rename store variables in the future without breaking the router
    adapters: {
        // How to toggle loading
        loading: (store, isLoading) => isLoading ? store.showLoading() : store.hideLoading(),
        
        // How to get auth state
        getAuthInitialized: (store) => store.authInitialized,
        getCurrentUser: (store) => store.currentUser,
        roleKey: 'role', // The property name in currentUser object
        
        // Logic for redirection
        getDefaultDestination: (store) => store.getDefaultDestination,
        
        // Logic for permissions
        checkPermission: (store, requiredRoles, routeName) => {
            return store.checkPermission(requiredRoles, routeName)
        },
        
        // Logic for claims
        checkClaim: (store, role) => store.currentUser?.claims?.[role],
        refreshClaims: (store) => store.refreshUserClaims()
    },

    // E. (Optional) Provide a loader for default error pages (404, 500)
    // If you don't provide this, you must define 404/500 routes in your 'routes' array manually
    viewLoader: (name) => lazy(name, 'errors')
})

export default router