// ============================================================================
// @generated by Totistack
// @last-modified: 2026-02-12
// ============================================================================

// ============================================================================
// CONSTANTS & CONFIGURATION
// ============================================================================

/**
 * Cache configuration - 1 HOUR TTL for production performance
 * Users rarely change roles, so hourly sync is sufficient
 */
export const CACHE_CONFIG = {
  PROFILE_TTL: 60 * 60 * 1000,        // 1 hour in milliseconds
  TOKEN_REFRESH_INTERVAL: 45 * 60 * 1000, // Refresh token after 45 minutes
  CLAIM_CHECK_INTERVAL: 30 * 60 * 1000,   // Check claims every 30 minutes
  MAX_CACHE_SIZE: 50,                    // Max cached profiles (for multi-tenant)
};

/**
 * Role hierarchy and permissions mapping
 * Centralized role configuration - SINGLE SOURCE OF TRUTH
 */
export const ROLE_CONFIG = {
  // All available roles in the system
  roles: {
    USER: 'user',
    PRACTINIOER: 'practinioer',
    ADMIN: 'admin',
  },

  // Human-readable display names
  displayNames: {
    user: 'Client',
    practitioner: 'Nangura N Bertha',
    admin: 'System Administrator',
  },

  // Route destinations per role (for guest-only redirects)
  defaultDestinations: {
    user: '/my',
    practitioner: '/pra',
    admin: '/pra',
  },

  // Role hierarchy (higher number = more privileges)
  hierarchy: {
    user: 0,
    practitioner: 3,
    admin: 4,
  },

  // Roles that require custom claims verification
  sensitiveRoles: ['admin', 'practitioner', 'auditor'],

  // Route-level permission matrix
  // Format: routeName: allowedRoles
  routePermissions: {
    'Dashboard': ['user', 'practitioner', 'admin'],
    'UserManagement': ['practitioner', 'admin'],
    'UserManagement': ['admin'],
    'AdminPanel': ['admin'],
    'KYCVerification': ['admin'],
  },
};
